/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/amazon/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Product Information */
        get: operations["get_AmazonProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/product/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Product Variants */
        get: operations["get_AmazonProductVariants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/product/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Product Stock Estimates */
        get: operations["get_AmazonStockEstimates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/product/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Product Sales Estimates */
        get: operations["get_AmazonSalesEstimates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/product/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Product Top Reviews */
        get: operations["get_AmazonProductReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Amazon Products */
        get: operations["get_AmazonProductSearchResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Search Autocomplete Results */
        get: operations["get_AmazonSearchAutocompleteResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Product Category Taxonomy */
        get: operations["get_AmazonProductCategoryTaxonomy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Product Category Information */
        get: operations["get_AmazonProductCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Seller Information */
        get: operations["get_AmazonSeller"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/author": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Amazon Author Information */
        get: operations["get_AmazonAuthor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Amazon Deals
         * @description Retrieve current deals from Amazon. Returns a paginated list of products currently on deal, including deal-specific information like discount percentages and deal badges.
         */
        get: operations["get_AmazonDeals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_AmazonProduct: {
        parameters: {
            query?: {
                /** @description The ASIN for a product (e.g. B01HY0JA3G) */
                asin?: string;
                /** @description The Amazon URL for a product */
                url?: string;
                /** @description The GTIN (ISBN, UPC or EAN code) for a product */
                gtin?: string;
                /** @description The domain for fetching product data, defaults to US */
                domain?: string;
            };
            header: {
                /** @description API Key for authentication */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon product information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProduct: {
                                title?: string;
                                subtitle?: string;
                                brand?: string;
                                url?: string;
                                asin?: string;
                                isPrime?: boolean;
                                isNew?: boolean;
                                price?: {
                                    symbol: string;
                                    value: number;
                                    currency: string;
                                    display: string;
                                };
                                mainImageUrl?: string;
                                imageUrls?: string[];
                                rating?: number;
                                ratingsTotal?: number;
                                featureBullets?: string[];
                                categories?: {
                                    id?: string;
                                    name?: string;
                                    url?: string;
                                    breadcrumbPath?: string;
                                }[];
                                seller?: {
                                    sellerId?: string;
                                    name?: string;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonProductVariants: {
        parameters: {
            query?: {
                /** @description The ASIN for a product (e.g. B01HY0JA3G) */
                asin?: string;
                /** @description The Amazon URL for a product */
                url?: string;
                /** @description The GTIN (ISBN, UPC or EAN code) for a product */
                gtin?: string;
                /** @description The domain for fetching product data, defaults to US */
                domain?: string;
            };
            header: {
                /** @description API Key for authentication */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon product variants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProduct: {
                                variants?: {
                                    asin?: string;
                                    text?: string;
                                    url?: string;
                                    attributes?: {
                                        name?: string;
                                        value?: string;
                                    }[];
                                    price?: {
                                        symbol: string;
                                        value: number;
                                        currency: string;
                                        display: string;
                                    };
                                }[];
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonStockEstimates: {
        parameters: {
            query?: {
                /** @description The ASIN for a product (e.g. B01HY0JA3G) */
                asin?: string;
                /** @description The Amazon URL for a product */
                url?: string;
                /** @description The GTIN (ISBN, UPC or EAN code) for a product */
                gtin?: string;
                /** @description The domain for fetching product data, defaults to US */
                domain?: string;
            };
            header: {
                /** @description API Key for authentication */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon product stock estimates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProduct: {
                                stockEstimate?: {
                                    offerId?: string;
                                    inStock: boolean;
                                    stockLevel?: number;
                                    availabilityMessage?: string;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonSalesEstimates: {
        parameters: {
            query?: {
                /** @description The ASIN for a product (e.g. B01HY0JA3G) */
                asin?: string;
                /** @description The Amazon URL for a product */
                url?: string;
                /** @description The GTIN (ISBN, UPC or EAN code) for a product */
                gtin?: string;
                /** @description The domain for fetching product data, defaults to US */
                domain?: string;
            };
            header: {
                /** @description API Key for authentication */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon product sales estimates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProduct: {
                                salesEstimate?: {
                                    weeklyUnitSales?: number;
                                    monthlyUnitSales?: number;
                                    annualUnitSales?: number;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonProductReviews: {
        parameters: {
            query?: {
                /** @description The ASIN for a product (e.g. B01HY0JA3G) */
                asin?: string;
                /** @description The Amazon URL for a product */
                url?: string;
                /** @description The GTIN (ISBN, UPC or EAN code) for a product */
                gtin?: string;
                /** @description The domain for fetching product data, defaults to US */
                domain?: string;
            };
            header: {
                /** @description API Key for authentication */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon product top reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProduct: {
                                topReviews?: {
                                    id?: string;
                                    title?: string;
                                    body?: string;
                                    imageUrls?: string[];
                                    videos?: {
                                        posterImageUrl?: string;
                                        url?: string;
                                    }[];
                                    rating?: number;
                                    helpfulVotes?: number;
                                    verifiedPurchase?: boolean;
                                    reviewer?: {
                                        id?: string;
                                        name?: string;
                                        url?: string;
                                    };
                                }[];
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonProductSearchResults: {
        parameters: {
            query: {
                /** @description The search term for fetching search results */
                searchTerm: string;
                /** @description The domain for fetching search results data, defaults to US */
                domain?: string;
                /** @description An optional category ID used to filter search results */
                categoryId?: string;
                /** @description The page number requested for product results */
                page?: number;
                /** @description Optionally limit the products results, typically between 20-40 results */
                limit?: number;
                /** @description Minimum price filter */
                minPrice?: number;
                /** @description Maximum price filter */
                maxPrice?: number;
                /** @description Product conditions (NEW, USED, RENEWED) - comma separated */
                conditions?: string;
                /** @description Sort order (FEATURED, MOST_RECENT, PRICE_ASCENDING, PRICE_DESCENDING, AVERAGE_CUSTOMER_REVIEW) */
                sort?: string;
            };
            header: {
                /** @description API key for accessing Canopy GraphQL endpoint */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon product search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProductSearchResults: {
                                availableRefinements?: {
                                    name?: string;
                                    options?: {
                                        name?: string;
                                    }[];
                                }[];
                                productResults?: {
                                    results?: {
                                        title?: string;
                                        url?: string;
                                        asin?: string;
                                        price?: {
                                            symbol: string;
                                            value: number;
                                            currency: string;
                                            display: string;
                                        };
                                        mainImageUrl?: string;
                                        rating?: number;
                                        ratingsTotal?: number;
                                        isPrime?: boolean;
                                        sponsored?: boolean;
                                    }[];
                                    pageInfo?: {
                                        currentPage?: number;
                                        totalPages?: number;
                                        hasNextPage?: boolean;
                                        hasPrevPage?: boolean;
                                    };
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonSearchAutocompleteResults: {
        parameters: {
            query: {
                /** @description The search term for fetching autocomplete results */
                searchTerm: string;
                /** @description The domain for fetching autocomplete data, defaults to US */
                domain?: string;
                /** @description The search autocomplete_alias in the amazon url parameter */
                category?: string;
            };
            header: {
                /** @description API key for accessing Canopy GraphQL endpoint */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon search autocomplete results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonSearchAutocompleteResults: {
                                suggestion: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonProductCategoryTaxonomy: {
        parameters: {
            query?: {
                /** @description The domain for fetching product category taxonomy, defaults to US */
                domain?: string;
            };
            header: {
                /** @description API key for accessing Canopy GraphQL endpoint */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns root level Amazon product categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProductCategoryTaxonomy: {
                                id: string;
                                name: string;
                                url: string;
                                breadcrumbPath: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonProductCategory: {
        parameters: {
            query: {
                /** @description The category ID, typically a number but may also be a string in certain cases */
                categoryId: string;
                /** @description The domain for fetching product category data, defaults to US */
                domain?: string;
                /** @description The page number requested for product results */
                page?: number;
                /** @description Sort order (FEATURED, MOST_RECENT, PRICE_ASCENDING, PRICE_DESCENDING, AVERAGE_CUSTOMER_REVIEW) */
                sort?: string;
            };
            header: {
                /** @description API key for accessing Canopy GraphQL endpoint */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon product category information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonProductCategory: {
                                id?: string;
                                name?: string;
                                url?: string;
                                breadcrumbPath?: string;
                                subcategories?: {
                                    id?: string;
                                    name?: string;
                                    url?: string;
                                    breadcrumbPath?: string;
                                }[];
                                productResults?: {
                                    results?: {
                                        title?: string;
                                        url?: string;
                                        asin?: string;
                                        price?: {
                                            symbol: string;
                                            value: number;
                                            currency: string;
                                            display: string;
                                        };
                                        mainImageUrl?: string;
                                        rating?: number;
                                        ratingsTotal?: number;
                                        isPrime?: boolean;
                                        sponsored?: boolean;
                                    }[];
                                    pageInfo?: {
                                        currentPage?: number;
                                        totalPages?: number;
                                        hasNextPage?: boolean;
                                        hasPrevPage?: boolean;
                                    };
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonSeller: {
        parameters: {
            query: {
                /** @description The seller ID for a product (e.g. A34JY1ZNKUG942) */
                sellerId: string;
                /** @description The domain for fetching seller data, defaults to US */
                domain?: string;
                /** @description The page number requested for product results */
                page?: number;
            };
            header: {
                /** @description API key for accessing Canopy GraphQL endpoint */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon seller information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonSeller: {
                                sellerId?: string;
                                name?: string;
                                logoUrl?: string;
                                phone?: string;
                                rating?: number;
                                about?: string;
                                productResults?: {
                                    results?: {
                                        title?: string;
                                        url?: string;
                                        asin?: string;
                                        price?: {
                                            symbol: string;
                                            value: number;
                                            currency: string;
                                            display: string;
                                        };
                                        mainImageUrl?: string;
                                        rating?: number;
                                        ratingsTotal?: number;
                                        isPrime?: boolean;
                                        sponsored?: boolean;
                                    }[];
                                    pageInfo?: {
                                        currentPage?: number;
                                        totalPages?: number;
                                        hasNextPage?: boolean;
                                        hasPrevPage?: boolean;
                                    };
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonAuthor: {
        parameters: {
            query: {
                /** @description The asin ID for the author (e.g. B017M7UJX6) */
                asin: string;
                /** @description The domain for fetching author data, defaults to US */
                domain?: string;
                /** @description The page number requested for book results */
                page?: number;
            };
            header: {
                /** @description API key for accessing Canopy GraphQL endpoint */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon author information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonAuthor: {
                                name?: string;
                                url?: string;
                                imageUrl?: string;
                                biography?: string;
                                bookResults?: {
                                    results?: {
                                        title?: string;
                                        url?: string;
                                        asin?: string;
                                        price?: {
                                            symbol: string;
                                            value: number;
                                            currency: string;
                                            display: string;
                                        };
                                        mainImageUrl?: string;
                                        rating?: number;
                                        ratingsTotal?: number;
                                        isPrime?: boolean;
                                        sponsored?: boolean;
                                        authors?: {
                                            name?: string;
                                            url?: string;
                                        }[];
                                    }[];
                                    pageInfo?: {
                                        currentPage?: number;
                                        totalPages?: number;
                                        hasNextPage?: boolean;
                                        hasPrevPage?: boolean;
                                    };
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_AmazonDeals: {
        parameters: {
            query?: {
                /** @description The domain for fetching deals data, defaults to US. Supported values: US, UK, CA, DE, FR, IT, ES, AU, IN, MX, BR, JP */
                domain?: string;
                /** @description The page number requested for product results */
                page?: number;
                /** @description Optionally limit the products results. Typically between 20-40 results will be available per page if no limit is applied. */
                limit?: number;
            };
            header: {
                /** @description API key for accessing Canopy GraphQL endpoint */
                "API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns Amazon deals with product information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            amazonDeals: {
                                productResults?: {
                                    results?: {
                                        title?: string;
                                        url?: string;
                                        asin?: string;
                                        price?: {
                                            symbol: string;
                                            value: number;
                                            currency: string;
                                            display: string;
                                        };
                                        recommendedRetailPrice?: {
                                            symbol: string;
                                            value: number;
                                            currency: string;
                                            display: string;
                                        };
                                        mainImageUrl?: string;
                                    }[];
                                    pageInfo?: {
                                        currentPage?: number;
                                        totalPages?: number;
                                        hasNextPage?: boolean;
                                        hasPrevPage?: boolean;
                                    };
                                };
                            };
                        };
                    };
                };
            };
            /** @description Input Validation Error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7001 */
                            code: number;
                            /** @example Input Validation Error */
                            message: string;
                            path: string[];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        errors: {
                            /** @example 7003 */
                            code: number;
                            /** @example Unauthorized */
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal Server Error - request failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
