// Bundles each widget entry in widgets/ into a self-contained HTML document
// and emits it as a TypeScript string module under src/widgets/ (gitignored),
// where the resource files in src/resources/(ui)/widget/ import it.
// Runs before `xmcp build --cf` (see package.json scripts).
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const WIDGETS = ["product", "search", "offers", "reviews", "bestsellers", "deals"];

const css = readFileSync(join(root, "widgets", "base.css"), "utf8");
mkdirSync(join(root, "src", "widgets"), { recursive: true });

for (const name of WIDGETS) {
  const result = await build({
    entryPoints: [join(root, "widgets", `${name}.ts`)],
    bundle: true,
    format: "esm",
    minify: true,
    target: "es2020",
    write: false,
  });
  // Prevent the inlined bundle from terminating the surrounding <script> tag.
  const js = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script type="module">${js}</script>
</body>
</html>`;
  writeFileSync(
    join(root, "src", "widgets", `${name}.ts`),
    `// Generated by scripts/build-widgets.mjs — do not edit.\nexport const html = ${JSON.stringify(html)};\n`,
  );
  console.log(`built widget ${name} (${(html.length / 1024).toFixed(1)} KB)`);
}
